### PR TITLE
PAC-1142: fixed free shipping

### PR DESCRIPTION
**Pull request by powatagdev**
Due to bug in adapter code order cannot be placed when shipping is set to free shipping. Bug is fixed now.

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @powatagdev,

Thanks, your PR has just been merged and the changes will be available soon.

Regards

**Comment by powatagdev** [comment]
Thanks @Quetzacoalt91 

Will this include the missing file "powatag/api/v1/.htaccess" ?

Regards

**Comment by Quetzacoalt91** [comment]
Unfortunately, this issue is not related to the content of the repo GitHub, but to the cron which downloads the module and escape (?) the hidden files. The team in charge of this Cron has been warned.

**Comment by powatagdev** [comment]
Can you provide me with contact details for this team?
Is there an indication of how long it will take them to come up with a solution. We just need to inform any customers busy using the module that the latest version will not work for them.

**Comment by Quetzacoalt91** [comment]
It is the addons team, who also manage PrestaShop Addons. (I won't give you specific email address across GitHub, but you ask to your partner manager to provide ;) )

**Pull request merged**
